// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.28.2
// source: protos/tendor-service/contractors.proto

package contractors

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ContractorServiceClient is the client API for ContractorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ContractorServiceClient interface {
	SubmitBid(ctx context.Context, in *SubmitBidRequest, opts ...grpc.CallOption) (*BidResponse, error)
	GetBidsForTender(ctx context.Context, in *GetBidsRequest, opts ...grpc.CallOption) (*BidsListResponse, error)
	GetMyBids(ctx context.Context, in *GetMyBidsRequest, opts ...grpc.CallOption) (*BidsListResponse, error)
}

type contractorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewContractorServiceClient(cc grpc.ClientConnInterface) ContractorServiceClient {
	return &contractorServiceClient{cc}
}

func (c *contractorServiceClient) SubmitBid(ctx context.Context, in *SubmitBidRequest, opts ...grpc.CallOption) (*BidResponse, error) {
	out := new(BidResponse)
	err := c.cc.Invoke(ctx, "/tender.ContractorService/SubmitBid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contractorServiceClient) GetBidsForTender(ctx context.Context, in *GetBidsRequest, opts ...grpc.CallOption) (*BidsListResponse, error) {
	out := new(BidsListResponse)
	err := c.cc.Invoke(ctx, "/tender.ContractorService/GetBidsForTender", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contractorServiceClient) GetMyBids(ctx context.Context, in *GetMyBidsRequest, opts ...grpc.CallOption) (*BidsListResponse, error) {
	out := new(BidsListResponse)
	err := c.cc.Invoke(ctx, "/tender.ContractorService/GetMyBids", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContractorServiceServer is the server API for ContractorService service.
// All implementations must embed UnimplementedContractorServiceServer
// for forward compatibility
type ContractorServiceServer interface {
	SubmitBid(context.Context, *SubmitBidRequest) (*BidResponse, error)
	GetBidsForTender(context.Context, *GetBidsRequest) (*BidsListResponse, error)
	GetMyBids(context.Context, *GetMyBidsRequest) (*BidsListResponse, error)
	mustEmbedUnimplementedContractorServiceServer()
}

// UnimplementedContractorServiceServer must be embedded to have forward compatible implementations.
type UnimplementedContractorServiceServer struct {
}

func (UnimplementedContractorServiceServer) SubmitBid(context.Context, *SubmitBidRequest) (*BidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitBid not implemented")
}
func (UnimplementedContractorServiceServer) GetBidsForTender(context.Context, *GetBidsRequest) (*BidsListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBidsForTender not implemented")
}
func (UnimplementedContractorServiceServer) GetMyBids(context.Context, *GetMyBidsRequest) (*BidsListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMyBids not implemented")
}
func (UnimplementedContractorServiceServer) mustEmbedUnimplementedContractorServiceServer() {}

// UnsafeContractorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContractorServiceServer will
// result in compilation errors.
type UnsafeContractorServiceServer interface {
	mustEmbedUnimplementedContractorServiceServer()
}

func RegisterContractorServiceServer(s grpc.ServiceRegistrar, srv ContractorServiceServer) {
	s.RegisterService(&ContractorService_ServiceDesc, srv)
}

func _ContractorService_SubmitBid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitBidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractorServiceServer).SubmitBid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tender.ContractorService/SubmitBid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractorServiceServer).SubmitBid(ctx, req.(*SubmitBidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContractorService_GetBidsForTender_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBidsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractorServiceServer).GetBidsForTender(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tender.ContractorService/GetBidsForTender",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractorServiceServer).GetBidsForTender(ctx, req.(*GetBidsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContractorService_GetMyBids_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyBidsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractorServiceServer).GetMyBids(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tender.ContractorService/GetMyBids",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractorServiceServer).GetMyBids(ctx, req.(*GetMyBidsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ContractorService_ServiceDesc is the grpc.ServiceDesc for ContractorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContractorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tender.ContractorService",
	HandlerType: (*ContractorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitBid",
			Handler:    _ContractorService_SubmitBid_Handler,
		},
		{
			MethodName: "GetBidsForTender",
			Handler:    _ContractorService_GetBidsForTender_Handler,
		},
		{
			MethodName: "GetMyBids",
			Handler:    _ContractorService_GetMyBids_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/tendor-service/contractors.proto",
}
