// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.28.2
// source: protos/fourth/fourth.proto

package fourth_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Test4Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Meassage string `protobuf:"bytes,1,opt,name=meassage,proto3" json:"meassage,omitempty"`
}

func (x *Test4Req) Reset() {
	*x = Test4Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_fourth_fourth_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Test4Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Test4Req) ProtoMessage() {}

func (x *Test4Req) ProtoReflect() protoreflect.Message {
	mi := &file_protos_fourth_fourth_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Test4Req.ProtoReflect.Descriptor instead.
func (*Test4Req) Descriptor() ([]byte, []int) {
	return file_protos_fourth_fourth_proto_rawDescGZIP(), []int{0}
}

func (x *Test4Req) GetMeassage() string {
	if x != nil {
		return x.Meassage
	}
	return ""
}

type Test4Res struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Meassage string `protobuf:"bytes,1,opt,name=meassage,proto3" json:"meassage,omitempty"`
}

func (x *Test4Res) Reset() {
	*x = Test4Res{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_fourth_fourth_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Test4Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Test4Res) ProtoMessage() {}

func (x *Test4Res) ProtoReflect() protoreflect.Message {
	mi := &file_protos_fourth_fourth_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Test4Res.ProtoReflect.Descriptor instead.
func (*Test4Res) Descriptor() ([]byte, []int) {
	return file_protos_fourth_fourth_proto_rawDescGZIP(), []int{1}
}

func (x *Test4Res) GetMeassage() string {
	if x != nil {
		return x.Meassage
	}
	return ""
}

var File_protos_fourth_fourth_proto protoreflect.FileDescriptor

var file_protos_fourth_fourth_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x66, 0x6f, 0x75, 0x72, 0x74, 0x68, 0x2f,
	0x66, 0x6f, 0x75, 0x72, 0x74, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x66, 0x6f,
	0x75, 0x72, 0x74, 0x68, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x26, 0x0a, 0x08, 0x54,
	0x65, 0x73, 0x74, 0x34, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x65, 0x61, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x65, 0x61, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x22, 0x26, 0x0a, 0x08, 0x54, 0x65, 0x73, 0x74, 0x34, 0x52, 0x65, 0x73, 0x12,
	0x1a, 0x0a, 0x08, 0x6d, 0x65, 0x61, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6d, 0x65, 0x61, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x4a, 0x0a, 0x0d, 0x46,
	0x6f, 0x75, 0x72, 0x74, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x39, 0x0a, 0x05,
	0x54, 0x65, 0x73, 0x74, 0x34, 0x12, 0x17, 0x2e, 0x66, 0x6f, 0x75, 0x72, 0x74, 0x68, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x34, 0x52, 0x65, 0x71, 0x1a, 0x17,
	0x2e, 0x66, 0x6f, 0x75, 0x72, 0x74, 0x68, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x54,
	0x65, 0x73, 0x74, 0x34, 0x52, 0x65, 0x73, 0x42, 0x22, 0x5a, 0x20, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x6f, 0x75,
	0x72, 0x74, 0x68, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_protos_fourth_fourth_proto_rawDescOnce sync.Once
	file_protos_fourth_fourth_proto_rawDescData = file_protos_fourth_fourth_proto_rawDesc
)

func file_protos_fourth_fourth_proto_rawDescGZIP() []byte {
	file_protos_fourth_fourth_proto_rawDescOnce.Do(func() {
		file_protos_fourth_fourth_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_fourth_fourth_proto_rawDescData)
	})
	return file_protos_fourth_fourth_proto_rawDescData
}

var file_protos_fourth_fourth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_fourth_fourth_proto_goTypes = []interface{}{
	(*Test4Req)(nil), // 0: fourthservice.Test4Req
	(*Test4Res)(nil), // 1: fourthservice.Test4Res
}
var file_protos_fourth_fourth_proto_depIdxs = []int32{
	0, // 0: fourthservice.FourthService.Test4:input_type -> fourthservice.Test4Req
	1, // 1: fourthservice.FourthService.Test4:output_type -> fourthservice.Test4Res
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_fourth_fourth_proto_init() }
func file_protos_fourth_fourth_proto_init() {
	if File_protos_fourth_fourth_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_fourth_fourth_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Test4Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_fourth_fourth_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Test4Res); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_fourth_fourth_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_fourth_fourth_proto_goTypes,
		DependencyIndexes: file_protos_fourth_fourth_proto_depIdxs,
		MessageInfos:      file_protos_fourth_fourth_proto_msgTypes,
	}.Build()
	File_protos_fourth_fourth_proto = out.File
	file_protos_fourth_fourth_proto_rawDesc = nil
	file_protos_fourth_fourth_proto_goTypes = nil
	file_protos_fourth_fourth_proto_depIdxs = nil
}
