// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.28.2
// source: protos/second/second.proto

package second_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SecondServiceClient is the client API for SecondService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SecondServiceClient interface {
	Test2(ctx context.Context, in *Test2Req, opts ...grpc.CallOption) (*Test2Res, error)
}

type secondServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSecondServiceClient(cc grpc.ClientConnInterface) SecondServiceClient {
	return &secondServiceClient{cc}
}

func (c *secondServiceClient) Test2(ctx context.Context, in *Test2Req, opts ...grpc.CallOption) (*Test2Res, error) {
	out := new(Test2Res)
	err := c.cc.Invoke(ctx, "/secondservice.SecondService/Test2", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SecondServiceServer is the server API for SecondService service.
// All implementations must embed UnimplementedSecondServiceServer
// for forward compatibility
type SecondServiceServer interface {
	Test2(context.Context, *Test2Req) (*Test2Res, error)
	mustEmbedUnimplementedSecondServiceServer()
}

// UnimplementedSecondServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSecondServiceServer struct {
}

func (UnimplementedSecondServiceServer) Test2(context.Context, *Test2Req) (*Test2Res, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Test2 not implemented")
}
func (UnimplementedSecondServiceServer) mustEmbedUnimplementedSecondServiceServer() {}

// UnsafeSecondServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SecondServiceServer will
// result in compilation errors.
type UnsafeSecondServiceServer interface {
	mustEmbedUnimplementedSecondServiceServer()
}

func RegisterSecondServiceServer(s grpc.ServiceRegistrar, srv SecondServiceServer) {
	s.RegisterService(&SecondService_ServiceDesc, srv)
}

func _SecondService_Test2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Test2Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecondServiceServer).Test2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/secondservice.SecondService/Test2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecondServiceServer).Test2(ctx, req.(*Test2Req))
	}
	return interceptor(ctx, in, info, handler)
}

// SecondService_ServiceDesc is the grpc.ServiceDesc for SecondService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SecondService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "secondservice.SecondService",
	HandlerType: (*SecondServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Test2",
			Handler:    _SecondService_Test2_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/second/second.proto",
}
